--liquibase formatted sql

--changeset demo.dba:20260921-01 labels:demo,foundation context:demo runOnChange:false
CREATE TABLE demo_customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(200 CHAR) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_demo_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_demo_customers_name UNIQUE (customer_name)
);

--rollback DROP TABLE demo_customers CASCADE CONSTRAINTS;
