--liquibase formatted sql

--changeset demo.dba:20260921-02 labels:demo,dependent-object context:demo runOnChange:false
--comment Depends on DEMO_CUSTOMERS (changeset 20260921-01).
CREATE TABLE demo_customer_addresses (
    address_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    address_type VARCHAR2(30 CHAR) NOT NULL,
    address_line_1 VARCHAR2(200 CHAR) NOT NULL,
    city VARCHAR2(100 CHAR) NOT NULL,
    country_code CHAR(2 CHAR) NOT NULL,
    CONSTRAINT pk_demo_customer_addresses PRIMARY KEY (address_id),
    CONSTRAINT fk_demo_address_customer
        FOREIGN KEY (customer_id) REFERENCES demo_customers (customer_id),
    CONSTRAINT uq_demo_customer_address_type UNIQUE (customer_id, address_type)
);

--rollback DROP TABLE demo_customer_addresses CASCADE CONSTRAINTS;
