--liquibase formatted sql

--changeset demo.dba:20260921-03 labels:demo,application-change context:demo runOnChange:false
--comment A realistic application change checked into Git by the DBA team. Depends on DEMO_CUSTOMERS.
CREATE TABLE demo_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    order_status VARCHAR2(30 CHAR) DEFAULT 'NEW' NOT NULL,
    order_total NUMBER(12,2) DEFAULT 0 NOT NULL,
    ordered_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_demo_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_demo_order_customer
        FOREIGN KEY (customer_id) REFERENCES demo_customers (customer_id),
    CONSTRAINT ck_demo_orders_status CHECK (order_status IN ('NEW', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_demo_orders_total CHECK (order_total >= 0)
);

CREATE INDEX ix_demo_orders_customer_ordered
    ON demo_orders (customer_id, ordered_at);

--rollback DROP TABLE demo_orders CASCADE CONSTRAINTS;
